# House Price Competition Project.
# General

    ## 1.Problem Definition
    * Goal: Predict the sales price of each house
    ### 1.2 Data Pre Processing 
    * Shape / Info/ Describe

    ## 2. Feature Selections:
    * Choose feature selection for machine learning (build model)
    * Need to use "featue Engineeering" to identify features needed

    ## 3. Spliting the datasets
    ### 3.1. datashet -> X, y
    * `data` : dataset
    * `x` : `Data[features']`
    * `y` : Target variable `SalePrice`
    ### 3.2. X,y -> X_train, y_train, X_valid, y_valid
    
    ## 4. Trainning Machine Leaning Model

    ## 5.  Model Evaluation

In [154]:
import pandas as pd 
import numpy as np

In [155]:
data = pd.read_csv("./Data/train.csv")

In [156]:
data = pd.read_csv("./Data/train.csv", index_col = "Id") #Adjust Index Column

In [157]:
data.head()

MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
Id                                                                    
1           60       RL         65.0     8450   Pave   NaN      Reg   
2           20       RL         80.0     9600   Pave   NaN      Reg   
3           60       RL         68.0    11250   Pave   NaN      IR1   
4           70       RL         60.0     9550   Pave   NaN      IR1   
5           60       RL         84.0    14260   Pave   NaN      IR1   

   LandContour Utilities LotConfig  ... PoolArea PoolQC Fence MiscFeature  \
Id                                  ...                                     
1          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
2          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   
3          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
4          Lvl    AllPub    Corner  ...        0    NaN   NaN         NaN   
5          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   

   MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
Id                                                             
1        0      2    2008        WD         Normal     208500  
2        0      5    2007        WD         Normal     181500  
3        0      9    2008        WD         Normal     223500  
4        0      2    2006        WD        Abnorml     140000  
5        0     12    2008        WD         Normal     250000  

[5 rows x 80 columns]

In [158]:
data.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'PavedDrive', 'Wo

In [159]:
data.shape

(1460, 80)

In [160]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1460 entries, 1 to 1460
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   MSSubClass     1460 non-null   int64  
 1   MSZoning       1460 non-null   object 
 2   LotFrontage    1201 non-null   float64
 3   LotArea        1460 non-null   int64  
 4   Street         1460 non-null   object 
 5   Alley          91 non-null     object 
 6   LotShape       1460 non-null   object 
 7   LandContour    1460 non-null   object 
 8   Utilities      1460 non-null   object 
 9   LotConfig      1460 non-null   object 
 10  LandSlope      1460 non-null   object 
 11  Neighborhood   1460 non-null   object 
 12  Condition1     1460 non-null   object 
 13  Condition2     1460 non-null   object 
 14  BldgType       1460 non-null   object 
 15  HouseStyle     1460 non-null   object 
 16  OverallQual    1460 non-null   int64  
 17  OverallCond    1460 non-null   int64  
 18  YearBuil

In [161]:
data.describe(include="all")

MSSubClass MSZoning  LotFrontage        LotArea Street Alley  \
count   1460.000000     1460  1201.000000    1460.000000   1460    91   
unique          NaN        5          NaN            NaN      2     2   
top             NaN       RL          NaN            NaN   Pave  Grvl   
freq            NaN     1151          NaN            NaN   1454    50   
mean      56.897260      NaN    70.049958   10516.828082    NaN   NaN   
std       42.300571      NaN    24.284752    9981.264932    NaN   NaN   
min       20.000000      NaN    21.000000    1300.000000    NaN   NaN   
25%       20.000000      NaN    59.000000    7553.500000    NaN   NaN   
50%       50.000000      NaN    69.000000    9478.500000    NaN   NaN   
75%       70.000000      NaN    80.000000   11601.500000    NaN   NaN   
max      190.000000      NaN   313.000000  215245.000000    NaN   NaN   

       LotShape LandContour Utilities LotConfig  ...     PoolArea PoolQC  \
count      1460        1460      1460      1460  ...  1460.000000      7   
unique        4           4         2         5  ...          NaN      3   
top         Reg         Lvl    AllPub    Inside  ...          NaN     Gd   
freq        925        1311      1459      1052  ...          NaN      3   
mean        NaN         NaN       NaN       NaN  ...     2.758904    NaN   
std         NaN         NaN       NaN       NaN  ...    40.177307    NaN   
min         NaN         NaN       NaN       NaN  ...     0.000000    NaN   
25%         NaN         NaN       NaN       NaN  ...     0.000000    NaN   
50%         NaN         NaN       NaN       NaN  ...     0.000000    NaN   
75%         NaN         NaN       NaN       NaN  ...     0.000000    NaN   
max         NaN         NaN       NaN       NaN  ...   738.000000    NaN   

        Fence MiscFeature       MiscVal       MoSold       YrSold  SaleType  \
count     281          54   1460.000000  1460.000000  1460.000000      1460   
unique      4           4           NaN          NaN          NaN         9   
top     MnPrv        Shed           NaN          NaN          NaN        WD   
freq      157          49           NaN          NaN          NaN      1267   
mean      NaN         NaN     43.489041     6.321918  2007.815753       NaN   
std       NaN         NaN    496.123024     2.703626     1.328095       NaN   
min       NaN         NaN      0.000000     1.000000  2006.000000       NaN   
25%       NaN         NaN      0.000000     5.000000  2007.000000       NaN   
50%       NaN         NaN      0.000000     6.000000  2008.000000       NaN   
75%       NaN         NaN      0.000000     8.000000  2009.000000       NaN   
max       NaN         NaN  15500.000000    12.000000  2010.000000       NaN   

        SaleCondition      SalePrice  
count            1460    1460.000000  
unique              6            NaN  
top            Normal            NaN  
freq             1198            NaN  
mean              NaN  180921.195890  
std               NaN   79442.502883  
min               NaN   34900.000000  
25%               NaN  129975.000000  
50%               NaN  163000.000000  
75%               NaN  214000.000000  
max               NaN  755000.000000  

[11 rows x 80 columns]

## 2 Feature Selections:
* Choose feature selection for machine learning (build model) 

In [162]:
# creat list feature
features = ['LotArea','YearBuilt','1stFlrSF', '2ndFlrSF','FullBath', 'BedroomAbvGr','TotRmsAbvGrd']

## 3. Spliting dataset into X and Y

In [163]:
X = data[features]
y = data['SalePrice']

In [164]:
X.head()

LotArea  YearBuilt  1stFlrSF  2ndFlrSF  FullBath  BedroomAbvGr  \
Id                                                                   
1      8450       2003       856       854         2             3   
2      9600       1976      1262         0         2             3   
3     11250       2001       920       866         2             3   
4      9550       1915       961       756         1             3   
5     14260       2000      1145      1053         2             4   

    TotRmsAbvGrd  
Id                
1              8  
2              6  
3              6  
4              7  
5              9

In [165]:
y.head()


Id
1    208500
2    181500
3    223500
4    140000
5    250000
Name: SalePrice, dtype: int64

#### 3.2. X,y -> X_train, y_train, X_valid, y_valid

In [166]:
from sklearn.model_selection import train_test_split
#train_size=0.8 nghĩa là 80% data sử dụng để train, còn lại test_size 0.2
X_train, X_valid,y_train, y_valid = train_test_split(X,y, train_size=0.8, test_size = 0.2, random_state=0)
#Funct train_test_split sẽ tách ngẫu nhiên 80% để tạo X_train y train, nếu fix random_state=0 để kết quả đòng nhất

### 4. Trainning Machine Leaning Model

#### Model DecisionTreeRegressor

In [167]:
from sklearn.tree import DecisionTreeRegressor
#Sau khi import, phải gọi classs nó ra - Khỏi tạo model, fix random_state
dt_model = DecisionTreeRegressor(random_state=1)

In [168]:
#Fit traning data int model
dt_model.fit(X_train, y_train)

DecisionTreeRegressor(random_state=1)

In [169]:
#Thực hiện dự đoán
y_preds = dt_model.predict(X_valid.head())

In [170]:
y_preds

array([335000., 140200., 119000., 207500., 112000.])

In [171]:
#tạo Data frame để so sánh giá trị thực y_valid và giá trị dự đoán y_preds
#Tạo dataframe dictionaries
pd.DataFrame({'y': y_valid.head(), 'y_preds': y_preds})

y   y_preds
Id                   
530  200624  335000.0
492  133000  140200.0
460  110000  119000.0
280  192000  207500.0
656   88000  112000.0

#### Model RandomForestRegressor

In [172]:
from sklearn.ensemble import RandomForestRegressor
rf_model = RandomForestRegressor(random_state=1)
rf_model.fit(X_train, y_train)

RandomForestRegressor(random_state=1)

In [173]:
rf_val_preds = rf_model.predict(X_valid.head())

In [174]:
rf_val_preds

array([271690., 155039., 122024., 188915.,  91147.])

In [175]:
pd.DataFrame({'y1': y_valid.head(), 'y1_preds': rf_val_preds})

y1  y1_preds
Id                   
530  200624  271690.0
492  133000  155039.0
460  110000  122024.0
280  192000  188915.0
656   88000   91147.0

### Predict with a new Input

In [176]:
X_valid.head()

LotArea  YearBuilt  1stFlrSF  2ndFlrSF  FullBath  BedroomAbvGr  \
Id                                                                    
530    32668       1957      2515         0         3             4   
492     9490       1941       958       620         1             3   
460     7015       1950       979       224         1             3   
280    10005       1977      1156       866         2             4   
656     1680       1971       525       567         1             3   

     TotRmsAbvGrd  
Id                 
530             9  
492             5  
460             5  
280             8  
656             6

In [177]:
rf_model.predict([[6969,2001,1000,800,4,5,8]])
#Hàm predict kì vọng mảng hai chiều nên nếu chỉ predict 1 giá trị thì phải để hai ngoặc

E:\Anaconda\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([193992.32])

# Sumarize - 5  Model Evaluation

In [178]:
# creat list feature
import pandas as pd 
import numpy as np
data = pd.read_csv("./Data/train.csv")
features = ['LotArea','YearBuilt','1stFlrSF', '2ndFlrSF','FullBath', 'BedroomAbvGr','TotRmsAbvGrd']
X = data[features]
y = data['SalePrice']

In [179]:
from sklearn.model_selection import train_test_split
# evaluate the model on the test set
X_train, X_valid,y_train, y_valid = train_test_split(X,y, train_size=0.8, test_size = 0.2, random_state=0)

In [180]:
from sklearn.tree import DecisionTreeRegressor
dt_model = DecisionTreeRegressor(random_state=1).fit(X_train, y_train)
# evaluate the model on the test set
print("Test set score: {:.2f}".format(dt_model.score(X_valid, y_valid)))

Test set score: 0.53


In [181]:
from sklearn.ensemble import RandomForestRegressor
rf_model = RandomForestRegressor(random_state=1).fit(X_train, y_train)
# evaluate the model on the test set
print("Test set score: {:.2f}".format(rf_model.score(X_valid, y_valid)))

Test set score: 0.78


In [182]:
from sklearn.datasets import make_blobs
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# create a synthetic dataset
X, y = make_blobs(random_state=0)
X_train, X_valid,y_train, y_valid = train_test_split(X,y, train_size=0.8, test_size = 0.2, random_state=0)
# instantiate a model and fit it to the training set
logreg = LogisticRegression().fit(X_train, y_train)
# evaluate the model on the test set
print("Test set score: {:.2f}".format(logreg.score(X_valid, y_valid)))

Test set score: 0.95


In [184]:
from sklearn.metrics import mean_squared_error
print ('RMSE is: \n', mean_squared_error(y_valid, predictions))

NameError: name 'predictions' is not defined